[package]
name = "vim-syntax"
version = "0.1.0"
authors = ["hejack0207 <hejack0207@sina.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex-style = { version="0.1.0", path="../regex-style" }
peg = "0.6.2"